import cv2 as cv
import sys

"""
    LA DETECCIÓN DE OBJETOS SE TRABAJA A PARTIR DE MODELOS IA YA ENTRENADOS,
    ESTO CON LA FINALIDAD DE FACILITAR LA UBICACIÓN DE LOS OBJETOS EN UN
    ESPACIO FÍSICO DETERMINADO.
"""


